grpc:
    server:
        port: 9001
        reflection-service-enabled: true
    client:
        grpcItemService:
            address: static://localhost:9001
            negotiation-type: plaintext
        grpcUserService:
            address: static://localhost:9001
            negotiation-type: plaintext
server:
    error:
        include-stacktrace: always
        whitelabel:
            enabled: false
    port: 8081
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: postgresql
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgresql
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL81Dialect
                format_sql: false
                jdbc:
                    lob:
                        non_contextual_creation: true
                use_sql_comments: false
        show_sql: false
    sql:
        init:
            platform: postgres
