grpc:
  server:
    port: 9001
    reflection-service-enabled: true
    security:
      enabled: true
      key-store: classpath:keystore.p12
      key-store-password: austin
      key-store-format: PKCS12
      client-auth: require
      trust-store-format: PKCS12
      trust-store: classpath:truststore.p12
      trust-store-password: austin
server:
  port: 8080

logging:
  level:
    root: debug

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgresql
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
        use_sql_comments: false
    show_sql: false
  sql:
    init:
      platform: postgres